#!/bin/bash -x
# install nf-core modules used by the mpas pipeline
# MDS 4/13/2023

nf-core modules install blast/blastn
nf-core modules install blast/makeblastdb
nf-core modules install custom/dumpsoftwareversions
nf-core modules install fastqc
nf-core modules install multiqc
