#!/bin/bash -x

nextflow run main.nf -resume --metadata input/AK_metadata.xlsx -profile singularity,local
# nextflow run main.nf -resume --metadata input/AK_metadata.xlsx -profile singularity,local,test
# nextflow run main.nf -resume --metadata input/AK_metadata.xlsx -profile conda
