#!/bin/bash -x

nextflow run main.nf -resume --metadata input/AK_metadata.xlsx -profile conda,local
# nextflow run main.nf -resume --metadata input/AK_metadata.xlsx -profile singularity,stenglein
# nextflow run main.nf -resume --metadata input/AK_metadata.xlsx -profile singularity,stenglein,test
# nextflow run main.nf -resume --metadata input/AK_metadata.xlsx -profile conda
