name: R_conda_environment
channels:
  - conda-forge
  
dependencies:
  - conda-forge::r-base=4.1.2
  - conda-forge::r-tidyverse=1.3.1
  - conda-forge::r-openxlsx=4.2.5
  - conda-forge::r-readxl=1.3.1
