name: R_conda_environment
channels:
  - conda-forge
  
dependencies:
  - conda-forge::r-base=4.4.1
  - conda-forge::r-tidyverse=2.0.0
  - conda-forge::r-openxlsx=4.2.7
  - conda-forge::r-readxl=1.4.3
