#!/bin/bash
#
# Push singularity images to sylabs cloud
#

#### To push this image to the singularity library 

# I first had to create a singularity library account and login as described [here](https://sylabs.io/guides/latest/user-guide/cloud_library.html?highlight=push#overview)

# Do a remote login to singularity cloud library
# this uses access token created at sylabs cloud library site.  These expire every few months so may need to create a new one.
singularity remote login

# modify version number as appropriate
singularity push -D "A singularity image containing tidyverse and a few other R packages" r_tools.sif library://stenglein-lab/r_tools/r_tools:1.0.0

# push the python tools image
singularity push -D "A singularity image containing python 3.10.6 and several modules" python_tools.sif library://stenglein-lab/python_tools/python_tools:1.0.0

